trigger:
  paths:
   exclude:
     - manifest.json
  tags: 
   include:
     - "*"

pool:
  vmImage: 'windows-latest'

variables:
  projectName: 'MoeACG.Jellyfin.Plugin'
  solution: '$(projectName).sln'
  buildConfiguration: 'Release'

steps:
- task: PowerShell@2
  displayName: Set the tag name as an environment variable
  inputs:
    targetType: 'inline'
    script: |
      $VersionTag = git describe --tags
      Write-Host "##vso[task.setvariable variable=Version.Tag]$VersionTag"
    pwsh: true
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(solution)'
    arguments: '-c $(buildConfiguration) -o $(Build.BinariesDirectory) -p:Version=$(Version.Tag)'
    zipAfterPublish: false
    modifyOutputPath: false
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/$(projectName).dll'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(projectName).zip'
    replaceExistingArchive: true
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/FSharp.Core.dll'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(projectName).zip'
    replaceExistingArchive: false
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
